version: '1'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: HotelHackathonMyDatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3306:3306
    expose:
      - 3306
      - 33060
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    image: amazoncorretto:17
    ports:
      - 8080:8080
    expose:
      - 8080
    restart: always
    depends_on:
      - db
    entrypoint: ["java", "-jar", "./target/app.jar"]

volumes:
  db_data:
