INSERT INTO servico_item (nome, valor) VALUES ('Massagem Completa', 250.00);
INSERT INTO servico_item (nome, valor) VALUES ('Café da Manhã', 65.00);
INSERT INTO servico_item (nome, valor) VALUES ('Manicure', 85.00);
INSERT INTO servico_item (nome, valor) VALUES ('Almoço', 65.00);
INSERT INTO servico_item (nome, valor) VALUES ('Jantar', 85.00);
INSERT INTO servico_item (nome, valor) VALUES ('Refrigerantes', 8.00);
INSERT INTO servico_item (nome, valor) VALUES ('Sucos', 11.00);
INSERT INTO servico_item (nome, valor) VALUES ('Cervejas Nacionais', 12.00);
INSERT INTO servico_item (nome, valor) VALUES ('Cervejas Importadas', 20.00);
INSERT INTO servico_item (nome, valor) VALUES ('Caipiroska', 35.00);